version: '3'

services:
  db:
    image: postgres:15.1
    container_name: postgres-db
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=email@email.com

# volumes:
#   postgres-db:
#     external: true

# external: true, utiliza un volumen que ya ha sido creado
#           se elimina la linea, si se quiere crear uno nuevo