version: '3'

# services:
#   mongodb:
#     image: mongo:6.0
#     container_name: pokemon-db
#     volumes:
#       - poke-vol:/data/db
#     ports:
#       - 27017:27017
#     restart: always

# mongodb://localhost:27017 - tableplus conecction


services:
  mongodb:
    image: mongo:6.0
    container_name: ${MONGO_DB_NAME}
    volumes:
      - poke-vol:/data/db
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ['--auth']
    restart: always

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    ports:
      - 8080:8081
    restart: always

  poke-app:
    depends_on:
      - mongodb
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      - MONGODB=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:${PORT_DB}
      - DBNAME=${MONGO_DB_NAME}
    restart: always

# mongodb://zane:123@pokemon-db:27017

volumes:
  poke-vol:
    external: false